credentials:
  usernames:
    warotasawa:
      email: warot.asawa@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Warot Asawa
      password: W@r0t!234 # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - warot.asawa@gmail.com
